/**
 * 경량 이모지 데이터
 * 자주 사용하는 이모지만 포함 (약 200개)
 */

export interface EmojiItem {
  emoji: string;
  name: string;
  keywords: string[];
  category: string;
}

export const EMOJI_DATA: EmojiItem[] = [
  // Smileys & People
  { emoji: '😀', name: 'grinning', keywords: ['happy', 'smile', 'joy'], category: 'smileys' },
  { emoji: '😃', name: 'grinning_eyes', keywords: ['happy', 'joy', 'laugh'], category: 'smileys' },
  { emoji: '😄', name: 'grinning_eyes_smile', keywords: ['happy', 'joy', 'laugh'], category: 'smileys' },
  { emoji: '😁', name: 'beaming_eyes', keywords: ['happy', 'joy'], category: 'smileys' },
  { emoji: '😆', name: 'squinting_laugh', keywords: ['happy', 'laugh'], category: 'smileys' },
  { emoji: '😅', name: 'sweat_smile', keywords: ['happy', 'sweat'], category: 'smileys' },
  { emoji: '🤣', name: 'rolling_laugh', keywords: ['laugh', 'funny'], category: 'smileys' },
  { emoji: '😂', name: 'tears_joy', keywords: ['laugh', 'cry', 'happy'], category: 'smileys' },
  { emoji: '🙂', name: 'slight_smile', keywords: ['smile', 'happy'], category: 'smileys' },
  { emoji: '🙃', name: 'upside_down', keywords: ['silly', 'funny'], category: 'smileys' },
  { emoji: '😉', name: 'wink', keywords: ['wink', 'flirt'], category: 'smileys' },
  { emoji: '😊', name: 'smiling_eyes', keywords: ['happy', 'smile', 'cute'], category: 'smileys' },
  { emoji: '😇', name: 'halo', keywords: ['angel', 'innocent'], category: 'smileys' },
  { emoji: '🥰', name: 'smiling_hearts', keywords: ['love', 'happy'], category: 'smileys' },
  { emoji: '😍', name: 'heart_eyes', keywords: ['love', 'beautiful'], category: 'smileys' },
  { emoji: '🤩', name: 'star_eyes', keywords: ['star', 'amazed'], category: 'smileys' },
  { emoji: '😘', name: 'kiss', keywords: ['kiss', 'love'], category: 'smileys' },
  { emoji: '😗', name: 'kissing', keywords: ['kiss'], category: 'smileys' },
  { emoji: '😚', name: 'kissing_closed_eyes', keywords: ['kiss', 'love'], category: 'smileys' },
  { emoji: '😙', name: 'kissing_smiling_eyes', keywords: ['kiss', 'love'], category: 'smileys' },
  { emoji: '😋', name: 'savoring', keywords: ['yum', 'delicious'], category: 'smileys' },
  { emoji: '😛', name: 'tongue', keywords: ['tongue', 'silly'], category: 'smileys' },
  { emoji: '😜', name: 'wink_tongue', keywords: ['wink', 'tongue', 'silly'], category: 'smileys' },
  { emoji: '🤪', name: 'zany', keywords: ['crazy', 'silly'], category: 'smileys' },
  { emoji: '😝', name: 'squinting_tongue', keywords: ['tongue', 'silly'], category: 'smileys' },
  { emoji: '🤑', name: 'money_mouth', keywords: ['money', 'rich'], category: 'smileys' },
  { emoji: '🤗', name: 'hugging', keywords: ['hug', 'love'], category: 'smileys' },
  { emoji: '🤭', name: 'hand_over_mouth', keywords: ['shush', 'secret'], category: 'smileys' },
  { emoji: '🤫', name: 'shushing', keywords: ['shush', 'quiet'], category: 'smileys' },
  { emoji: '🤔', name: 'thinking', keywords: ['think', 'wonder'], category: 'smileys' },
  { emoji: '🤐', name: 'zipper_mouth', keywords: ['quiet', 'secret'], category: 'smileys' },
  { emoji: '🤨', name: 'raised_eyebrow', keywords: ['suspicious', 'think'], category: 'smileys' },
  { emoji: '😐', name: 'neutral', keywords: ['neutral', 'meh'], category: 'smileys' },
  { emoji: '😑', name: 'expressionless', keywords: ['blank', 'neutral'], category: 'smileys' },
  { emoji: '😶', name: 'no_mouth', keywords: ['silent', 'quiet'], category: 'smileys' },
  { emoji: '😏', name: 'smirk', keywords: ['smirk', 'sly'], category: 'smileys' },
  { emoji: '😒', name: 'unamused', keywords: ['unhappy', 'sad'], category: 'smileys' },
  { emoji: '🙄', name: 'rolling_eyes', keywords: ['sarcastic', 'annoyed'], category: 'smileys' },
  { emoji: '😬', name: 'grimacing', keywords: ['grimace', 'awkward'], category: 'smileys' },
  { emoji: '🤥', name: 'lying', keywords: ['lie', 'fake'], category: 'smileys' },
  { emoji: '😌', name: 'relieved', keywords: ['relieved', 'calm'], category: 'smileys' },
  { emoji: '😔', name: 'pensive', keywords: ['sad', 'thoughtful'], category: 'smileys' },
  { emoji: '😪', name: 'sleepy', keywords: ['tired', 'sleepy'], category: 'smileys' },
  { emoji: '🤤', name: 'drooling', keywords: ['drool', 'hungry'], category: 'smileys' },
  { emoji: '😴', name: 'sleeping', keywords: ['sleep', 'tired'], category: 'smileys' },
  { emoji: '😷', name: 'mask', keywords: ['sick', 'mask'], category: 'smileys' },
  { emoji: '🤒', name: 'thermometer', keywords: ['sick', 'fever'], category: 'smileys' },
  { emoji: '🤕', name: 'bandage', keywords: ['hurt', 'injured'], category: 'smileys' },
  { emoji: '🤢', name: 'nauseated', keywords: ['sick', 'nauseous'], category: 'smileys' },
  { emoji: '🤮', name: 'vomiting', keywords: ['sick', 'vomit'], category: 'smileys' },
  { emoji: '🤧', name: 'sneezing', keywords: ['sick', 'sneeze'], category: 'smileys' },
  { emoji: '🥵', name: 'hot', keywords: ['hot', 'sweat'], category: 'smileys' },
  { emoji: '🥶', name: 'cold', keywords: ['cold', 'freeze'], category: 'smileys' },
  { emoji: '😵', name: 'dizzy', keywords: ['dizzy', 'confused'], category: 'smileys' },
  { emoji: '🤯', name: 'exploding', keywords: ['mind', 'blown'], category: 'smileys' },
  { emoji: '🤠', name: 'cowboy', keywords: ['cowboy', 'hat'], category: 'smileys' },
  { emoji: '🥳', name: 'party', keywords: ['party', 'celebration'], category: 'smileys' },
  { emoji: '😎', name: 'sunglasses', keywords: ['cool', 'shades'], category: 'smileys' },
  { emoji: '🤓', name: 'nerd', keywords: ['nerd', 'glasses'], category: 'smileys' },
  { emoji: '🧐', name: 'monocle', keywords: ['monocle', 'think'], category: 'smileys' },
  { emoji: '😕', name: 'confused', keywords: ['confused', 'sad'], category: 'smileys' },
  { emoji: '😟', name: 'worried', keywords: ['worried', 'anxious'], category: 'smileys' },
  { emoji: '🙁', name: 'slight_frown', keywords: ['sad', 'frown'], category: 'smileys' },
  { emoji: '😮', name: 'open_mouth', keywords: ['surprised', 'shocked'], category: 'smileys' },
  { emoji: '😯', name: 'hushed', keywords: ['surprised', 'quiet'], category: 'smileys' },
  { emoji: '😲', name: 'astonished', keywords: ['surprised', 'shocked'], category: 'smileys' },
  { emoji: '😳', name: 'flushed', keywords: ['embarrassed', 'blush'], category: 'smileys' },
  { emoji: '🥺', name: 'pleading', keywords: ['pleading', 'sad'], category: 'smileys' },
  { emoji: '😦', name: 'frown_open', keywords: ['sad', 'frown'], category: 'smileys' },
  { emoji: '😧', name: 'anguished', keywords: ['sad', 'pain'], category: 'smileys' },
  { emoji: '😨', name: 'fearful', keywords: ['scared', 'fear'], category: 'smileys' },
  { emoji: '😰', name: 'anxious_sweat', keywords: ['anxious', 'sweat'], category: 'smileys' },
  { emoji: '😥', name: 'sad_relieved', keywords: ['sad', 'relieved'], category: 'smileys' },
  { emoji: '😢', name: 'cry', keywords: ['sad', 'cry'], category: 'smileys' },
  { emoji: '😭', name: 'loudly_cry', keywords: ['sad', 'cry', 'tears'], category: 'smileys' },
  { emoji: '🤣', name: 'rolling_laugh', keywords: ['laugh', 'funny'], category: 'smileys' },
  { emoji: '😱', name: 'scream', keywords: ['scared', 'scream'], category: 'smileys' },
  { emoji: '😖', name: 'confounded', keywords: ['confused', 'frustrated'], category: 'smileys' },
  { emoji: '😣', name: 'persevere', keywords: ['persevere', 'struggle'], category: 'smileys' },
  { emoji: '😞', name: 'disappointed', keywords: ['sad', 'disappointed'], category: 'smileys' },
  { emoji: '😓', name: 'sweat', keywords: ['sweat', 'tired'], category: 'smileys' },
  { emoji: '😩', name: 'weary', keywords: ['tired', 'weary'], category: 'smileys' },
  { emoji: '😫', name: 'tired', keywords: ['tired', 'exhausted'], category: 'smileys' },
  { emoji: '🥱', name: 'yawning', keywords: ['tired', 'yawn'], category: 'smileys' },
  { emoji: '😤', name: 'triumph', keywords: ['triumph', 'proud'], category: 'smileys' },
  { emoji: '😡', name: 'pouting', keywords: ['angry', 'mad'], category: 'smileys' },
  { emoji: '😠', name: 'angry', keywords: ['angry', 'mad'], category: 'smileys' },
  { emoji: '🤬', name: 'swearing', keywords: ['angry', 'swear'], category: 'smileys' },
  { emoji: '😈', name: 'smiling_horns', keywords: ['devil', 'evil'], category: 'smileys' },
  { emoji: '👿', name: 'angry_horns', keywords: ['devil', 'angry'], category: 'smileys' },
  { emoji: '💀', name: 'skull', keywords: ['death', 'skull'], category: 'smileys' },
  { emoji: '☠️', name: 'skull_crossbones', keywords: ['death', 'danger'], category: 'smileys' },
  { emoji: '💩', name: 'poop', keywords: ['poop', 'funny'], category: 'smileys' },
  { emoji: '🤡', name: 'clown', keywords: ['clown', 'funny'], category: 'smileys' },
  { emoji: '👹', name: 'ogre', keywords: ['monster', 'ogre'], category: 'smileys' },
  { emoji: '👺', name: 'goblin', keywords: ['monster', 'goblin'], category: 'smileys' },
  { emoji: '👻', name: 'ghost', keywords: ['ghost', 'scary'], category: 'smileys' },
  { emoji: '👽', name: 'alien', keywords: ['alien', 'space'], category: 'smileys' },
  { emoji: '👾', name: 'alien_monster', keywords: ['alien', 'monster'], category: 'smileys' },
  { emoji: '🤖', name: 'robot', keywords: ['robot', 'tech'], category: 'smileys' },
  { emoji: '😺', name: 'grinning_cat', keywords: ['cat', 'happy'], category: 'animals' },
  { emoji: '😸', name: 'grinning_cat_eyes', keywords: ['cat', 'happy'], category: 'animals' },
  { emoji: '😹', name: 'joy_cat', keywords: ['cat', 'laugh'], category: 'animals' },
  { emoji: '😻', name: 'heart_eyes_cat', keywords: ['cat', 'love'], category: 'animals' },
  { emoji: '😼', name: 'smirk_cat', keywords: ['cat', 'smirk'], category: 'animals' },
  { emoji: '😽', name: 'kissing_cat', keywords: ['cat', 'kiss'], category: 'animals' },
  { emoji: '🙀', name: 'scream_cat', keywords: ['cat', 'scared'], category: 'animals' },
  { emoji: '😿', name: 'crying_cat', keywords: ['cat', 'sad'], category: 'animals' },
  { emoji: '😾', name: 'pouting_cat', keywords: ['cat', 'angry'], category: 'animals' },
  { emoji: '👋', name: 'wave', keywords: ['wave', 'hello', 'bye'], category: 'gestures' },
  { emoji: '🤚', name: 'raised_backhand', keywords: ['hand', 'stop'], category: 'gestures' },
  { emoji: '🖐️', name: 'hand_splayed', keywords: ['hand', 'five'], category: 'gestures' },
  { emoji: '✋', name: 'raised_hand', keywords: ['hand', 'stop', 'highfive'], category: 'gestures' },
  { emoji: '🖖', name: 'vulcan', keywords: ['spock', 'live'], category: 'gestures' },
  { emoji: '👌', name: 'ok_hand', keywords: ['ok', 'good'], category: 'gestures' },
  { emoji: '🤏', name: 'pinching', keywords: ['pinch', 'small'], category: 'gestures' },
  { emoji: '✌️', name: 'victory', keywords: ['victory', 'peace'], category: 'gestures' },
  { emoji: '🤞', name: 'crossed_fingers', keywords: ['luck', 'hope'], category: 'gestures' },
  { emoji: '🤟', name: 'love_you', keywords: ['love', 'ily'], category: 'gestures' },
  { emoji: '🤘', name: 'horns', keywords: ['rock', 'metal'], category: 'gestures' },
  { emoji: '🤙', name: 'call_me', keywords: ['call', 'phone'], category: 'gestures' },
  { emoji: '👈', name: 'point_left', keywords: ['left', 'point'], category: 'gestures' },
  { emoji: '👉', name: 'point_right', keywords: ['right', 'point'], category: 'gestures' },
  { emoji: '👆', name: 'point_up', keywords: ['up', 'point'], category: 'gestures' },
  { emoji: '🖕', name: 'middle_finger', keywords: ['middle', 'finger'], category: 'gestures' },
  { emoji: '👇', name: 'point_down', keywords: ['down', 'point'], category: 'gestures' },
  { emoji: '☝️', name: 'point_up_index', keywords: ['up', 'point'], category: 'gestures' },
  { emoji: '👍', name: 'thumbs_up', keywords: ['thumbs', 'up', 'good'], category: 'gestures' },
  { emoji: '👎', name: 'thumbs_down', keywords: ['thumbs', 'down', 'bad'], category: 'gestures' },
  { emoji: '✊', name: 'fist', keywords: ['fist', 'punch'], category: 'gestures' },
  { emoji: '👊', name: 'punch', keywords: ['punch', 'fist'], category: 'gestures' },
  { emoji: '🤛', name: 'fist_left', keywords: ['fist', 'left'], category: 'gestures' },
  { emoji: '🤜', name: 'fist_right', keywords: ['fist', 'right'], category: 'gestures' },
  { emoji: '👏', name: 'clap', keywords: ['clap', 'applause'], category: 'gestures' },
  { emoji: '🙌', name: 'raising_hands', keywords: ['raise', 'hands', 'celebration'], category: 'gestures' },
  { emoji: '👐', name: 'open_hands', keywords: ['open', 'hands'], category: 'gestures' },
  { emoji: '🤲', name: 'palms_up', keywords: ['palms', 'pray'], category: 'gestures' },
  { emoji: '🤝', name: 'handshake', keywords: ['handshake', 'deal'], category: 'gestures' },
  { emoji: '🙏', name: 'pray', keywords: ['pray', 'please'], category: 'gestures' },
  { emoji: '✍️', name: 'writing', keywords: ['write', 'pen'], category: 'gestures' },
  { emoji: '💪', name: 'muscle', keywords: ['muscle', 'strong'], category: 'gestures' },
  { emoji: '🦾', name: 'mechanical_arm', keywords: ['arm', 'robot'], category: 'gestures' },
  { emoji: '🦿', name: 'mechanical_leg', keywords: ['leg', 'robot'], category: 'gestures' },
  { emoji: '🦵', name: 'leg', keywords: ['leg'], category: 'gestures' },
  { emoji: '🦶', name: 'foot', keywords: ['foot'], category: 'gestures' },
  { emoji: '👂', name: 'ear', keywords: ['ear', 'hear'], category: 'gestures' },
  { emoji: '🦻', name: 'ear_hearing_aid', keywords: ['ear', 'hearing'], category: 'gestures' },
  { emoji: '👃', name: 'nose', keywords: ['nose', 'smell'], category: 'gestures' },
  { emoji: '🧠', name: 'brain', keywords: ['brain', 'think'], category: 'gestures' },
  { emoji: '🦷', name: 'tooth', keywords: ['tooth', 'teeth'], category: 'gestures' },
  { emoji: '🦴', name: 'bone', keywords: ['bone'], category: 'gestures' },
  { emoji: '👀', name: 'eyes', keywords: ['eyes', 'see'], category: 'gestures' },
  { emoji: '👁️', name: 'eye', keywords: ['eye', 'see'], category: 'gestures' },
  { emoji: '👅', name: 'tongue', keywords: ['tongue', 'taste'], category: 'gestures' },
  { emoji: '👄', name: 'lips', keywords: ['lips', 'kiss'], category: 'gestures' },
  { emoji: '💋', name: 'kiss_mark', keywords: ['kiss', 'love'], category: 'gestures' },
  { emoji: '💘', name: 'heart_arrow', keywords: ['love', 'heart'], category: 'symbols' },
  { emoji: '💝', name: 'heart_ribbon', keywords: ['love', 'gift'], category: 'symbols' },
  { emoji: '💖', name: 'sparkling_heart', keywords: ['love', 'sparkle'], category: 'symbols' },
  { emoji: '💗', name: 'growing_heart', keywords: ['love', 'grow'], category: 'symbols' },
  { emoji: '💓', name: 'beating_heart', keywords: ['love', 'beat'], category: 'symbols' },
  { emoji: '💞', name: 'revolving_hearts', keywords: ['love', 'revolve'], category: 'symbols' },
  { emoji: '💕', name: 'two_hearts', keywords: ['love', 'two'], category: 'symbols' },
  { emoji: '💟', name: 'heart_decoration', keywords: ['heart', 'decoration'], category: 'symbols' },
  { emoji: '❣️', name: 'heart_exclamation', keywords: ['heart', 'exclamation'], category: 'symbols' },
  { emoji: '💔', name: 'broken_heart', keywords: ['broken', 'sad'], category: 'symbols' },
  { emoji: '❤️', name: 'red_heart', keywords: ['love', 'red'], category: 'symbols' },
  { emoji: '🧡', name: 'orange_heart', keywords: ['love', 'orange'], category: 'symbols' },
  { emoji: '💛', name: 'yellow_heart', keywords: ['love', 'yellow'], category: 'symbols' },
  { emoji: '💚', name: 'green_heart', keywords: ['love', 'green'], category: 'symbols' },
  { emoji: '💙', name: 'blue_heart', keywords: ['love', 'blue'], category: 'symbols' },
  { emoji: '💜', name: 'purple_heart', keywords: ['love', 'purple'], category: 'symbols' },
  { emoji: '🖤', name: 'black_heart', keywords: ['love', 'black'], category: 'symbols' },
  { emoji: '🤍', name: 'white_heart', keywords: ['love', 'white'], category: 'symbols' },
  { emoji: '🤎', name: 'brown_heart', keywords: ['love', 'brown'], category: 'symbols' },
  { emoji: '💯', name: 'hundred', keywords: ['100', 'perfect'], category: 'symbols' },
  { emoji: '✅', name: 'check_mark', keywords: ['check', 'ok'], category: 'symbols' },
  { emoji: '❌', name: 'cross_mark', keywords: ['cross', 'wrong'], category: 'symbols' },
  { emoji: '⭕', name: 'red_circle', keywords: ['circle', 'red'], category: 'symbols' },
  { emoji: '🆗', name: 'ok_button', keywords: ['ok', 'good'], category: 'symbols' },
  { emoji: '🆕', name: 'new_button', keywords: ['new'], category: 'symbols' },
  { emoji: '🆓', name: 'free_button', keywords: ['free'], category: 'symbols' },
  { emoji: '🆒', name: 'cool_button', keywords: ['cool'], category: 'symbols' },
  { emoji: '🆙', name: 'up_button', keywords: ['up'], category: 'symbols' },
  { emoji: '🆚', name: 'vs_button', keywords: ['vs', 'versus'], category: 'symbols' },
  { emoji: '🈁', name: 'here_button', keywords: ['here'], category: 'symbols' },
  { emoji: '🈂️', name: 'service_charge', keywords: ['service'], category: 'symbols' },
  { emoji: '🈷️', name: 'monthly_amount', keywords: ['month'], category: 'symbols' },
  { emoji: '🈶', name: 'not_free', keywords: ['not', 'free'], category: 'symbols' },
  { emoji: '🈯', name: 'reserved', keywords: ['reserved'], category: 'symbols' },
  { emoji: '🉐', name: 'bargain', keywords: ['bargain'], category: 'symbols' },
  { emoji: '🈹', name: 'discount', keywords: ['discount'], category: 'symbols' },
  { emoji: '🈲', name: 'prohibited', keywords: ['prohibited'], category: 'symbols' },
  { emoji: '🉑', name: 'acceptable', keywords: ['acceptable'], category: 'symbols' },
  { emoji: '🈸', name: 'application', keywords: ['application'], category: 'symbols' },
  { emoji: '🈴', name: 'passing_grade', keywords: ['pass'], category: 'symbols' },
  { emoji: '🈳', name: 'vacancy', keywords: ['vacancy'], category: 'symbols' },
  { emoji: '㊗️', name: 'congratulations', keywords: ['congratulations'], category: 'symbols' },
  { emoji: '㊙️', name: 'secret', keywords: ['secret'], category: 'symbols' },
  { emoji: '🈺', name: 'open_business', keywords: ['open'], category: 'symbols' },
  { emoji: '🈵', name: 'no_vacancy', keywords: ['full'], category: 'symbols' },
  // Food & Drink
  { emoji: '🍕', name: 'pizza', keywords: ['pizza', 'food'], category: 'food' },
  { emoji: '🍔', name: 'hamburger', keywords: ['burger', 'food'], category: 'food' },
  { emoji: '🍟', name: 'fries', keywords: ['fries', 'food'], category: 'food' },
  { emoji: '🌭', name: 'hotdog', keywords: ['hotdog', 'food'], category: 'food' },
  { emoji: '🍿', name: 'popcorn', keywords: ['popcorn', 'movie'], category: 'food' },
  { emoji: '🧂', name: 'salt', keywords: ['salt', 'seasoning'], category: 'food' },
  { emoji: '🥓', name: 'bacon', keywords: ['bacon', 'food'], category: 'food' },
  { emoji: '🥚', name: 'egg', keywords: ['egg', 'food'], category: 'food' },
  { emoji: '🍳', name: 'fried_egg', keywords: ['egg', 'breakfast'], category: 'food' },
  { emoji: '🥞', name: 'pancakes', keywords: ['pancake', 'breakfast'], category: 'food' },
  { emoji: '🧇', name: 'waffle', keywords: ['waffle', 'breakfast'], category: 'food' },
  { emoji: '🥨', name: 'pretzel', keywords: ['pretzel', 'snack'], category: 'food' },
  { emoji: '🥯', name: 'bagel', keywords: ['bagel', 'bread'], category: 'food' },
  { emoji: '🥖', name: 'baguette', keywords: ['bread', 'french'], category: 'food' },
  { emoji: '🍞', name: 'bread', keywords: ['bread', 'food'], category: 'food' },
  { emoji: '🥐', name: 'croissant', keywords: ['croissant', 'bread'], category: 'food' },
  { emoji: '🥨', name: 'pretzel', keywords: ['pretzel', 'snack'], category: 'food' },
  { emoji: '🧀', name: 'cheese', keywords: ['cheese', 'food'], category: 'food' },
  { emoji: '🥗', name: 'salad', keywords: ['salad', 'healthy'], category: 'food' },
  { emoji: '🥙', name: 'stuffed_flatbread', keywords: ['wrap', 'food'], category: 'food' },
  { emoji: '🥪', name: 'sandwich', keywords: ['sandwich', 'food'], category: 'food' },
  { emoji: '🌮', name: 'taco', keywords: ['taco', 'mexican'], category: 'food' },
  { emoji: '🌯', name: 'burrito', keywords: ['burrito', 'mexican'], category: 'food' },
  { emoji: '🥫', name: 'canned_food', keywords: ['can', 'food'], category: 'food' },
  { emoji: '🍝', name: 'spaghetti', keywords: ['pasta', 'italian'], category: 'food' },
  { emoji: '🍜', name: 'steaming_bowl', keywords: ['ramen', 'noodles'], category: 'food' },
  { emoji: '🍲', name: 'pot_of_food', keywords: ['pot', 'food'], category: 'food' },
  { emoji: '🍛', name: 'curry', keywords: ['curry', 'food'], category: 'food' },
  { emoji: '🍣', name: 'sushi', keywords: ['sushi', 'japanese'], category: 'food' },
  { emoji: '🍱', name: 'bento', keywords: ['bento', 'japanese'], category: 'food' },
  { emoji: '🍚', name: 'rice', keywords: ['rice', 'food'], category: 'food' },
  { emoji: '🍙', name: 'rice_ball', keywords: ['rice', 'japanese'], category: 'food' },
  { emoji: '🍘', name: 'rice_cracker', keywords: ['cracker', 'snack'], category: 'food' },
  { emoji: '🍥', name: 'fish_cake', keywords: ['fish', 'cake'], category: 'food' },
  { emoji: '🥟', name: 'dumpling', keywords: ['dumpling', 'food'], category: 'food' },
  { emoji: '🥠', name: 'fortune_cookie', keywords: ['cookie', 'fortune'], category: 'food' },
  { emoji: '🥡', name: 'takeout_box', keywords: ['takeout', 'chinese'], category: 'food' },
  { emoji: '🦀', name: 'crab', keywords: ['crab', 'seafood'], category: 'food' },
  { emoji: '🦞', name: 'lobster', keywords: ['lobster', 'seafood'], category: 'food' },
  { emoji: '🦐', name: 'shrimp', keywords: ['shrimp', 'seafood'], category: 'food' },
  { emoji: '🦑', name: 'squid', keywords: ['squid', 'seafood'], category: 'food' },
  { emoji: '🦪', name: 'oyster', keywords: ['oyster', 'seafood'], category: 'food' },
  { emoji: '🍤', name: 'fried_shrimp', keywords: ['shrimp', 'fried'], category: 'food' },
  { emoji: '🍿', name: 'popcorn', keywords: ['popcorn', 'movie'], category: 'food' },
  { emoji: '🍩', name: 'doughnut', keywords: ['donut', 'sweet'], category: 'food' },
  { emoji: '🍪', name: 'cookie', keywords: ['cookie', 'sweet'], category: 'food' },
  { emoji: '🎂', name: 'birthday_cake', keywords: ['cake', 'birthday'], category: 'food' },
  { emoji: '🍰', name: 'cake', keywords: ['cake', 'sweet'], category: 'food' },
  { emoji: '🧁', name: 'cupcake', keywords: ['cupcake', 'sweet'], category: 'food' },
  { emoji: '🥧', name: 'pie', keywords: ['pie', 'sweet'], category: 'food' },
  { emoji: '🍫', name: 'chocolate', keywords: ['chocolate', 'sweet'], category: 'food' },
  { emoji: '🍬', name: 'candy', keywords: ['candy', 'sweet'], category: 'food' },
  { emoji: '🍭', name: 'lollipop', keywords: ['lollipop', 'sweet'], category: 'food' },
  { emoji: '🍮', name: 'custard', keywords: ['custard', 'sweet'], category: 'food' },
  { emoji: '🍯', name: 'honey', keywords: ['honey', 'sweet'], category: 'food' },
  { emoji: '🍼', name: 'baby_bottle', keywords: ['bottle', 'baby'], category: 'food' },
  { emoji: '🥛', name: 'milk', keywords: ['milk', 'drink'], category: 'food' },
  { emoji: '☕', name: 'coffee', keywords: ['coffee', 'drink'], category: 'food' },
  { emoji: '🍵', name: 'tea', keywords: ['tea', 'drink'], category: 'food' },
  { emoji: '🍶', name: 'sake', keywords: ['sake', 'drink'], category: 'food' },
  { emoji: '🍺', name: 'beer', keywords: ['beer', 'drink'], category: 'food' },
  { emoji: '🍻', name: 'beers', keywords: ['beer', 'cheers'], category: 'food' },
  { emoji: '🥂', name: 'champagne', keywords: ['champagne', 'celebration'], category: 'food' },
  { emoji: '🍷', name: 'wine', keywords: ['wine', 'drink'], category: 'food' },
  { emoji: '🥃', name: 'whiskey', keywords: ['whiskey', 'drink'], category: 'food' },
  { emoji: '🍸', name: 'cocktail', keywords: ['cocktail', 'drink'], category: 'food' },
  { emoji: '🍹', name: 'tropical_drink', keywords: ['tropical', 'drink'], category: 'food' },
  { emoji: '🧃', name: 'beverage_box', keywords: ['juice', 'drink'], category: 'food' },
  { emoji: '🧉', name: 'mate', keywords: ['mate', 'drink'], category: 'food' },
  { emoji: '🧊', name: 'ice', keywords: ['ice', 'cold'], category: 'food' },
  // Travel & Places
  { emoji: '✈️', name: 'airplane', keywords: ['airplane', 'flight'], category: 'travel' },
  { emoji: '🛫', name: 'airplane_departure', keywords: ['departure', 'flight'], category: 'travel' },
  { emoji: '🛬', name: 'airplane_arrival', keywords: ['arrival', 'flight'], category: 'travel' },
  { emoji: '🛩️', name: 'small_airplane', keywords: ['airplane', 'small'], category: 'travel' },
  { emoji: '🛸', name: 'ufo', keywords: ['ufo', 'alien'], category: 'travel' },
  { emoji: '🚁', name: 'helicopter', keywords: ['helicopter', 'flight'], category: 'travel' },
  { emoji: '🚀', name: 'rocket', keywords: ['rocket', 'space'], category: 'travel' },
  { emoji: '🛰️', name: 'satellite', keywords: ['satellite', 'space'], category: 'travel' },
  { emoji: '🚂', name: 'steam_locomotive', keywords: ['train', 'steam'], category: 'travel' },
  { emoji: '🚃', name: 'railway_car', keywords: ['train', 'car'], category: 'travel' },
  { emoji: '🚄', name: 'bullet_train', keywords: ['train', 'fast'], category: 'travel' },
  { emoji: '🚅', name: 'train', keywords: ['train', 'transport'], category: 'travel' },
  { emoji: '🚆', name: 'metro', keywords: ['metro', 'subway'], category: 'travel' },
  { emoji: '🚇', name: 'metro', keywords: ['metro', 'subway'], category: 'travel' },
  { emoji: '🚈', name: 'light_rail', keywords: ['rail', 'train'], category: 'travel' },
  { emoji: '🚉', name: 'station', keywords: ['station', 'train'], category: 'travel' },
  { emoji: '🚊', name: 'tram', keywords: ['tram', 'train'], category: 'travel' },
  { emoji: '🚝', name: 'monorail', keywords: ['monorail', 'train'], category: 'travel' },
  { emoji: '🚞', name: 'mountain_railway', keywords: ['mountain', 'train'], category: 'travel' },
  { emoji: '🚋', name: 'tram_car', keywords: ['tram', 'car'], category: 'travel' },
  { emoji: '🚌', name: 'bus', keywords: ['bus', 'transport'], category: 'travel' },
  { emoji: '🚍', name: 'oncoming_bus', keywords: ['bus', 'oncoming'], category: 'travel' },
  { emoji: '🚎', name: 'trolleybus', keywords: ['trolley', 'bus'], category: 'travel' },
  { emoji: '🚐', name: 'minibus', keywords: ['minibus', 'bus'], category: 'travel' },
  { emoji: '🚑', name: 'ambulance', keywords: ['ambulance', 'emergency'], category: 'travel' },
  { emoji: '🚒', name: 'fire_engine', keywords: ['fire', 'truck'], category: 'travel' },
  { emoji: '🚓', name: 'police_car', keywords: ['police', 'car'], category: 'travel' },
  { emoji: '🚔', name: 'oncoming_police_car', keywords: ['police', 'car'], category: 'travel' },
  { emoji: '🚕', name: 'taxi', keywords: ['taxi', 'car'], category: 'travel' },
  { emoji: '🚖', name: 'oncoming_taxi', keywords: ['taxi', 'oncoming'], category: 'travel' },
  { emoji: '🚗', name: 'car', keywords: ['car', 'vehicle'], category: 'travel' },
  { emoji: '🚘', name: 'oncoming_automobile', keywords: ['car', 'oncoming'], category: 'travel' },
  { emoji: '🚙', name: 'suv', keywords: ['suv', 'car'], category: 'travel' },
  { emoji: '🚚', name: 'delivery_truck', keywords: ['truck', 'delivery'], category: 'travel' },
  { emoji: '🚛', name: 'articulated_lorry', keywords: ['truck', 'lorry'], category: 'travel' },
  { emoji: '🚜', name: 'tractor', keywords: ['tractor', 'farm'], category: 'travel' },
  { emoji: '🏎️', name: 'racing_car', keywords: ['racing', 'car'], category: 'travel' },
  { emoji: '🏍️', name: 'motorcycle', keywords: ['motorcycle', 'bike'], category: 'travel' },
  { emoji: '🛵', name: 'motor_scooter', keywords: ['scooter', 'motor'], category: 'travel' },
  { emoji: '🦽', name: 'manual_wheelchair', keywords: ['wheelchair', 'accessibility'], category: 'travel' },
  { emoji: '🦼', name: 'motorized_wheelchair', keywords: ['wheelchair', 'motor'], category: 'travel' },
  { emoji: '🛴', name: 'scooter', keywords: ['scooter', 'kick'], category: 'travel' },
  { emoji: '🚲', name: 'bicycle', keywords: ['bike', 'bicycle'], category: 'travel' },
  { emoji: '🛺', name: 'auto_rickshaw', keywords: ['rickshaw', 'auto'], category: 'travel' },
  { emoji: '🚏', name: 'busstop', keywords: ['bus', 'stop'], category: 'travel' },
  { emoji: '🛣️', name: 'motorway', keywords: ['road', 'highway'], category: 'travel' },
  { emoji: '🛤️', name: 'railway_track', keywords: ['railway', 'track'], category: 'travel' },
  { emoji: '🛢️', name: 'oil_drum', keywords: ['oil', 'drum'], category: 'travel' },
  { emoji: '⛽', name: 'fuel_pump', keywords: ['gas', 'station'], category: 'travel' },
  { emoji: '🚨', name: 'rotating_light', keywords: ['police', 'siren'], category: 'travel' },
  { emoji: '🚥', name: 'traffic_light', keywords: ['traffic', 'light'], category: 'travel' },
  { emoji: '🚦', name: 'vertical_traffic_light', keywords: ['traffic', 'light'], category: 'travel' },
  { emoji: '🛑', name: 'stop_sign', keywords: ['stop', 'sign'], category: 'travel' },
  { emoji: '🚧', name: 'construction', keywords: ['construction', 'work'], category: 'travel' },
  { emoji: '⚓', name: 'anchor', keywords: ['anchor', 'ship'], category: 'travel' },
  { emoji: '⛵', name: 'sailboat', keywords: ['sailboat', 'boat'], category: 'travel' },
  { emoji: '🛶', name: 'canoe', keywords: ['canoe', 'boat'], category: 'travel' },
  { emoji: '🚤', name: 'speedboat', keywords: ['speedboat', 'boat'], category: 'travel' },
  { emoji: '🛳️', name: 'passenger_ship', keywords: ['ship', 'cruise'], category: 'travel' },
  { emoji: '⛴️', name: 'ferry', keywords: ['ferry', 'boat'], category: 'travel' },
  { emoji: '🛥️', name: 'motor_boat', keywords: ['boat', 'motor'], category: 'travel' },
  { emoji: '🚢', name: 'ship', keywords: ['ship', 'boat'], category: 'travel' },
  { emoji: '🏗️', name: 'building_construction', keywords: ['construction', 'building'], category: 'travel' },
  { emoji: '🏭', name: 'factory', keywords: ['factory', 'industrial'], category: 'travel' },
  { emoji: '🏯', name: 'japanese_castle', keywords: ['castle', 'japanese'], category: 'travel' },
  { emoji: '🏰', name: 'castle', keywords: ['castle', 'european'], category: 'travel' },
  { emoji: '🗼', name: 'tokyo_tower', keywords: ['tower', 'tokyo'], category: 'travel' },
  { emoji: '🗽', name: 'statue_of_liberty', keywords: ['statue', 'liberty'], category: 'travel' },
  { emoji: '⛪', name: 'church', keywords: ['church', 'religion'], category: 'travel' },
  { emoji: '🕌', name: 'mosque', keywords: ['mosque', 'islam'], category: 'travel' },
  { emoji: '🛕', name: 'hindu_temple', keywords: ['temple', 'hindu'], category: 'travel' },
  { emoji: '🕍', name: 'synagogue', keywords: ['synagogue', 'jewish'], category: 'travel' },
  { emoji: '⛩️', name: 'shinto_shrine', keywords: ['shrine', 'shinto'], category: 'travel' },
  { emoji: '🕋', name: 'kaaba', keywords: ['kaaba', 'islam'], category: 'travel' },
  { emoji: '⛲', name: 'fountain', keywords: ['fountain', 'water'], category: 'travel' },
  { emoji: '⛺', name: 'tent', keywords: ['tent', 'camping'], category: 'travel' },
  { emoji: '🌁', name: 'foggy', keywords: ['fog', 'weather'], category: 'travel' },
  { emoji: '🌃', name: 'night_with_stars', keywords: ['night', 'stars'], category: 'travel' },
  { emoji: '🏙️', name: 'cityscape', keywords: ['city', 'urban'], category: 'travel' },
  { emoji: '🌄', name: 'sunrise_over_mountains', keywords: ['sunrise', 'mountain'], category: 'travel' },
  { emoji: '🌅', name: 'sunrise', keywords: ['sunrise', 'morning'], category: 'travel' },
  { emoji: '🌆', name: 'cityscape_at_dusk', keywords: ['city', 'dusk'], category: 'travel' },
  { emoji: '🌇', name: 'sunset', keywords: ['sunset', 'evening'], category: 'travel' },
  { emoji: '🌉', name: 'bridge_at_night', keywords: ['bridge', 'night'], category: 'travel' },
  { emoji: '♨️', name: 'hotsprings', keywords: ['hot', 'springs'], category: 'travel' },
  { emoji: '🎠', name: 'carousel_horse', keywords: ['carousel', 'horse'], category: 'travel' },
  { emoji: '🎡', name: 'ferris_wheel', keywords: ['ferris', 'wheel'], category: 'travel' },
  { emoji: '🎢', name: 'roller_coaster', keywords: ['roller', 'coaster'], category: 'travel' },
  { emoji: '💈', name: 'barber', keywords: ['barber', 'pole'], category: 'travel' },
  { emoji: '🎪', name: 'circus_tent', keywords: ['circus', 'tent'], category: 'travel' },
  { emoji: '🚂', name: 'steam_locomotive', keywords: ['train', 'steam'], category: 'travel' },
  { emoji: '🚇', name: 'metro', keywords: ['metro', 'subway'], category: 'travel' },
  { emoji: '🚊', name: 'tram', keywords: ['tram', 'train'], category: 'travel' },
  { emoji: '🚝', name: 'monorail', keywords: ['monorail', 'train'], category: 'travel' },
  { emoji: '🚞', name: 'mountain_railway', keywords: ['mountain', 'train'], category: 'travel' },
  { emoji: '🚋', name: 'tram_car', keywords: ['tram', 'car'], category: 'travel' },
  { emoji: '🚌', name: 'bus', keywords: ['bus', 'transport'], category: 'travel' },
  { emoji: '🚍', name: 'oncoming_bus', keywords: ['bus', 'oncoming'], category: 'travel' },
  { emoji: '🚎', name: 'trolleybus', keywords: ['trolley', 'bus'], category: 'travel' },
  { emoji: '🚐', name: 'minibus', keywords: ['minibus', 'bus'], category: 'travel' },
  { emoji: '🚑', name: 'ambulance', keywords: ['ambulance', 'emergency'], category: 'travel' },
  { emoji: '🚒', name: 'fire_engine', keywords: ['fire', 'truck'], category: 'travel' },
  { emoji: '🚓', name: 'police_car', keywords: ['police', 'car'], category: 'travel' },
  { emoji: '🚔', name: 'oncoming_police_car', keywords: ['police', 'car'], category: 'travel' },
  { emoji: '🚕', name: 'taxi', keywords: ['taxi', 'car'], category: 'travel' },
  { emoji: '🚖', name: 'oncoming_taxi', keywords: ['taxi', 'oncoming'], category: 'travel' },
  { emoji: '🚗', name: 'car', keywords: ['car', 'vehicle'], category: 'travel' },
  { emoji: '🚘', name: 'oncoming_automobile', keywords: ['car', 'oncoming'], category: 'travel' },
  { emoji: '🚙', name: 'suv', keywords: ['suv', 'car'], category: 'travel' },
  { emoji: '🚚', name: 'delivery_truck', keywords: ['truck', 'delivery'], category: 'travel' },
  { emoji: '🚛', name: 'articulated_lorry', keywords: ['truck', 'lorry'], category: 'travel' },
  { emoji: '🚜', name: 'tractor', keywords: ['tractor', 'farm'], category: 'travel' },
  { emoji: '🏎️', name: 'racing_car', keywords: ['racing', 'car'], category: 'travel' },
  { emoji: '🏍️', name: 'motorcycle', keywords: ['motorcycle', 'bike'], category: 'travel' },
  { emoji: '🛵', name: 'motor_scooter', keywords: ['scooter', 'motor'], category: 'travel' },
  { emoji: '🦽', name: 'manual_wheelchair', keywords: ['wheelchair', 'accessibility'], category: 'travel' },
  { emoji: '🦼', name: 'motorized_wheelchair', keywords: ['wheelchair', 'motor'], category: 'travel' },
  { emoji: '🛴', name: 'scooter', keywords: ['scooter', 'kick'], category: 'travel' },
  { emoji: '🚲', name: 'bicycle', keywords: ['bike', 'bicycle'], category: 'travel' },
  { emoji: '🛺', name: 'auto_rickshaw', keywords: ['rickshaw', 'auto'], category: 'travel' },
  { emoji: '🚏', name: 'busstop', keywords: ['bus', 'stop'], category: 'travel' },
  { emoji: '🛣️', name: 'motorway', keywords: ['road', 'highway'], category: 'travel' },
  { emoji: '🛤️', name: 'railway_track', keywords: ['railway', 'track'], category: 'travel' },
  { emoji: '🛢️', name: 'oil_drum', keywords: ['oil', 'drum'], category: 'travel' },
  { emoji: '⛽', name: 'fuel_pump', keywords: ['gas', 'station'], category: 'travel' },
  { emoji: '🚨', name: 'rotating_light', keywords: ['police', 'siren'], category: 'travel' },
  { emoji: '🚥', name: 'traffic_light', keywords: ['traffic', 'light'], category: 'travel' },
  { emoji: '🚦', name: 'vertical_traffic_light', keywords: ['traffic', 'light'], category: 'travel' },
  { emoji: '🛑', name: 'stop_sign', keywords: ['stop', 'sign'], category: 'travel' },
  { emoji: '🚧', name: 'construction', keywords: ['construction', 'work'], category: 'travel' },
  { emoji: '⚓', name: 'anchor', keywords: ['anchor', 'ship'], category: 'travel' },
  { emoji: '⛵', name: 'sailboat', keywords: ['sailboat', 'boat'], category: 'travel' },
  { emoji: '🛶', name: 'canoe', keywords: ['canoe', 'boat'], category: 'travel' },
  { emoji: '🚤', name: 'speedboat', keywords: ['speedboat', 'boat'], category: 'travel' },
  { emoji: '🛳️', name: 'passenger_ship', keywords: ['ship', 'cruise'], category: 'travel' },
  { emoji: '⛴️', name: 'ferry', keywords: ['ferry', 'boat'], category: 'travel' },
  { emoji: '🛥️', name: 'motor_boat', keywords: ['boat', 'motor'], category: 'travel' },
  { emoji: '🚢', name: 'ship', keywords: ['ship', 'boat'], category: 'travel' },
  { emoji: '🏗️', name: 'building_construction', keywords: ['construction', 'building'], category: 'travel' },
  { emoji: '🏭', name: 'factory', keywords: ['factory', 'industrial'], category: 'travel' },
  { emoji: '🏯', name: 'japanese_castle', keywords: ['castle', 'japanese'], category: 'travel' },
  { emoji: '🏰', name: 'castle', keywords: ['castle', 'european'], category: 'travel' },
  { emoji: '🗼', name: 'tokyo_tower', keywords: ['tower', 'tokyo'], category: 'travel' },
  { emoji: '🗽', name: 'statue_of_liberty', keywords: ['statue', 'liberty'], category: 'travel' },
  { emoji: '⛪', name: 'church', keywords: ['church', 'religion'], category: 'travel' },
  { emoji: '🕌', name: 'mosque', keywords: ['mosque', 'islam'], category: 'travel' },
  { emoji: '🛕', name: 'hindu_temple', keywords: ['temple', 'hindu'], category: 'travel' },
  { emoji: '🕍', name: 'synagogue', keywords: ['synagogue', 'jewish'], category: 'travel' },
  { emoji: '⛩️', name: 'shinto_shrine', keywords: ['shrine', 'shinto'], category: 'travel' },
  { emoji: '🕋', name: 'kaaba', keywords: ['kaaba', 'islam'], category: 'travel' },
  { emoji: '⛲', name: 'fountain', keywords: ['fountain', 'water'], category: 'travel' },
  { emoji: '⛺', name: 'tent', keywords: ['tent', 'camping'], category: 'travel' },
  { emoji: '🌁', name: 'foggy', keywords: ['fog', 'weather'], category: 'travel' },
  { emoji: '🌃', name: 'night_with_stars', keywords: ['night', 'stars'], category: 'travel' },
  { emoji: '🏙️', name: 'cityscape', keywords: ['city', 'urban'], category: 'travel' },
  { emoji: '🌄', name: 'sunrise_over_mountains', keywords: ['sunrise', 'mountain'], category: 'travel' },
  { emoji: '🌅', name: 'sunrise', keywords: ['sunrise', 'morning'], category: 'travel' },
  { emoji: '🌆', name: 'cityscape_at_dusk', keywords: ['city', 'dusk'], category: 'travel' },
  { emoji: '🌇', name: 'sunset', keywords: ['sunset', 'evening'], category: 'travel' },
  { emoji: '🌉', name: 'bridge_at_night', keywords: ['bridge', 'night'], category: 'travel' },
  { emoji: '♨️', name: 'hotsprings', keywords: ['hot', 'springs'], category: 'travel' },
  { emoji: '🎠', name: 'carousel_horse', keywords: ['carousel', 'horse'], category: 'travel' },
  { emoji: '🎡', name: 'ferris_wheel', keywords: ['ferris', 'wheel'], category: 'travel' },
  { emoji: '🎢', name: 'roller_coaster', keywords: ['roller', 'coaster'], category: 'travel' },
  { emoji: '💈', name: 'barber', keywords: ['barber', 'pole'], category: 'travel' },
  { emoji: '🎪', name: 'circus_tent', keywords: ['circus', 'tent'], category: 'travel' },
  // Activities
  { emoji: '⚽', name: 'soccer', keywords: ['soccer', 'football'], category: 'activities' },
  { emoji: '🏀', name: 'basketball', keywords: ['basketball', 'sport'], category: 'activities' },
  { emoji: '🏈', name: 'football', keywords: ['football', 'american'], category: 'activities' },
  { emoji: '⚾', name: 'baseball', keywords: ['baseball', 'sport'], category: 'activities' },
  { emoji: '🥎', name: 'softball', keywords: ['softball', 'sport'], category: 'activities' },
  { emoji: '🎾', name: 'tennis', keywords: ['tennis', 'sport'], category: 'activities' },
  { emoji: '🏐', name: 'volleyball', keywords: ['volleyball', 'sport'], category: 'activities' },
  { emoji: '🏉', name: 'rugby', keywords: ['rugby', 'sport'], category: 'activities' },
  { emoji: '🥏', name: 'flying_disc', keywords: ['frisbee', 'disc'], category: 'activities' },
  { emoji: '🎱', name: 'pool', keywords: ['pool', 'billiards'], category: 'activities' },
  { emoji: '🏓', name: 'ping_pong', keywords: ['ping', 'pong', 'table', 'tennis'], category: 'activities' },
  { emoji: '🏸', name: 'badminton', keywords: ['badminton', 'sport'], category: 'activities' },
  { emoji: '🥅', name: 'goal_net', keywords: ['goal', 'net'], category: 'activities' },
  { emoji: '🏒', name: 'ice_hockey', keywords: ['hockey', 'ice'], category: 'activities' },
  { emoji: '🏑', name: 'field_hockey', keywords: ['hockey', 'field'], category: 'activities' },
  { emoji: '🥍', name: 'lacrosse', keywords: ['lacrosse', 'sport'], category: 'activities' },
  { emoji: '🏏', name: 'cricket', keywords: ['cricket', 'sport'], category: 'activities' },
  { emoji: '🥊', name: 'boxing_glove', keywords: ['boxing', 'glove'], category: 'activities' },
  { emoji: '🥋', name: 'martial_arts_uniform', keywords: ['martial', 'arts'], category: 'activities' },
  { emoji: '🥇', name: 'first_place', keywords: ['gold', 'medal'], category: 'activities' },
  { emoji: '🥈', name: 'second_place', keywords: ['silver', 'medal'], category: 'activities' },
  { emoji: '🥉', name: 'third_place', keywords: ['bronze', 'medal'], category: 'activities' },
  { emoji: '🏆', name: 'trophy', keywords: ['trophy', 'award'], category: 'activities' },
  { emoji: '🏅', name: 'medal', keywords: ['medal', 'award'], category: 'activities' },
  { emoji: '🎖️', name: 'military_medal', keywords: ['medal', 'military'], category: 'activities' },
  { emoji: '🏵️', name: 'rosette', keywords: ['rosette', 'award'], category: 'activities' },
  { emoji: '🎗️', name: 'reminder_ribbon', keywords: ['ribbon', 'reminder'], category: 'activities' },
  { emoji: '🎫', name: 'ticket', keywords: ['ticket', 'admission'], category: 'activities' },
  { emoji: '🎟️', name: 'admission_tickets', keywords: ['ticket', 'admission'], category: 'activities' },
  { emoji: '🎪', name: 'circus_tent', keywords: ['circus', 'tent'], category: 'activities' },
  { emoji: '🎭', name: 'performing_arts', keywords: ['theater', 'drama'], category: 'activities' },
  { emoji: '🩰', name: 'ballet_shoes', keywords: ['ballet', 'dance'], category: 'activities' },
  { emoji: '🎨', name: 'art', keywords: ['art', 'paint'], category: 'activities' },
  { emoji: '🎬', name: 'clapper', keywords: ['movie', 'film'], category: 'activities' },
  { emoji: '🎤', name: 'microphone', keywords: ['microphone', 'sing'], category: 'activities' },
  { emoji: '🎧', name: 'headphones', keywords: ['headphones', 'music'], category: 'activities' },
  { emoji: '🎼', name: 'musical_score', keywords: ['music', 'score'], category: 'activities' },
  { emoji: '🎹', name: 'musical_keyboard', keywords: ['piano', 'keyboard'], category: 'activities' },
  { emoji: '🥁', name: 'drum', keywords: ['drum', 'music'], category: 'activities' },
  { emoji: '🎷', name: 'saxophone', keywords: ['saxophone', 'music'], category: 'activities' },
  { emoji: '🎺', name: 'trumpet', keywords: ['trumpet', 'music'], category: 'activities' },
  { emoji: '🎸', name: 'guitar', keywords: ['guitar', 'music'], category: 'activities' },
  { emoji: '🪕', name: 'banjo', keywords: ['banjo', 'music'], category: 'activities' },
  { emoji: '🎻', name: 'violin', keywords: ['violin', 'music'], category: 'activities' },
  { emoji: '🎲', name: 'game_die', keywords: ['dice', 'game'], category: 'activities' },
  { emoji: '♟️', name: 'chess_pawn', keywords: ['chess', 'pawn'], category: 'activities' },
  { emoji: '🎯', name: 'dart', keywords: ['dart', 'target'], category: 'activities' },
  { emoji: '🎳', name: 'bowling', keywords: ['bowling', 'game'], category: 'activities' },
  { emoji: '🎮', name: 'video_game', keywords: ['game', 'video'], category: 'activities' },
  { emoji: '🎰', name: 'slot_machine', keywords: ['slot', 'machine'], category: 'activities' },
  { emoji: '🧩', name: 'jigsaw', keywords: ['puzzle', 'jigsaw'], category: 'activities' },
  // Objects
  { emoji: '💡', name: 'light_bulb', keywords: ['light', 'bulb', 'idea'], category: 'objects' },
  { emoji: '🔦', name: 'flashlight', keywords: ['flashlight', 'torch'], category: 'objects' },
  { emoji: '🕯️', name: 'candle', keywords: ['candle', 'light'], category: 'objects' },
  { emoji: '🧯', name: 'fire_extinguisher', keywords: ['fire', 'extinguisher'], category: 'objects' },
  { emoji: '🪔', name: 'diya_lamp', keywords: ['diya', 'lamp'], category: 'objects' },
  { emoji: '📱', name: 'iphone', keywords: ['phone', 'iphone'], category: 'objects' },
  { emoji: '📲', name: 'calling', keywords: ['phone', 'call'], category: 'objects' },
  { emoji: '☎️', name: 'phone', keywords: ['phone', 'telephone'], category: 'objects' },
  { emoji: '📞', name: 'telephone_receiver', keywords: ['phone', 'receiver'], category: 'objects' },
  { emoji: '📟', name: 'pager', keywords: ['pager', 'beep'], category: 'objects' },
  { emoji: '📠', name: 'fax', keywords: ['fax', 'machine'], category: 'objects' },
  { emoji: '🔋', name: 'battery', keywords: ['battery', 'power'], category: 'objects' },
  { emoji: '🔌', name: 'electric_plug', keywords: ['plug', 'electric'], category: 'objects' },
  { emoji: '💻', name: 'computer', keywords: ['computer', 'laptop'], category: 'objects' },
  { emoji: '🖥️', name: 'desktop_computer', keywords: ['computer', 'desktop'], category: 'objects' },
  { emoji: '🖨️', name: 'printer', keywords: ['printer', 'print'], category: 'objects' },
  { emoji: '⌨️', name: 'keyboard', keywords: ['keyboard', 'type'], category: 'objects' },
  { emoji: '🖱️', name: 'computer_mouse', keywords: ['mouse', 'computer'], category: 'objects' },
  { emoji: '🖲️', name: 'trackball', keywords: ['trackball', 'mouse'], category: 'objects' },
  { emoji: '🕹️', name: 'joystick', keywords: ['joystick', 'game'], category: 'objects' },
  { emoji: '🗜️', name: 'clamp', keywords: ['clamp', 'tool'], category: 'objects' },
  { emoji: '💾', name: 'floppy_disk', keywords: ['disk', 'save'], category: 'objects' },
  { emoji: '💿', name: 'cd', keywords: ['cd', 'disk'], category: 'objects' },
  { emoji: '📀', name: 'dvd', keywords: ['dvd', 'disk'], category: 'objects' },
  { emoji: '📼', name: 'vhs', keywords: ['vhs', 'tape'], category: 'objects' },
  { emoji: '📷', name: 'camera', keywords: ['camera', 'photo'], category: 'objects' },
  { emoji: '📸', name: 'camera_flash', keywords: ['camera', 'flash'], category: 'objects' },
  { emoji: '📹', name: 'video_camera', keywords: ['video', 'camera'], category: 'objects' },
  { emoji: '🎥', name: 'movie_camera', keywords: ['movie', 'camera'], category: 'objects' },
  { emoji: '📽️', name: 'film_projector', keywords: ['projector', 'film'], category: 'objects' },
  { emoji: '🎞️', name: 'film_strips', keywords: ['film', 'strips'], category: 'objects' },
  { emoji: '📞', name: 'telephone_receiver', keywords: ['phone', 'receiver'], category: 'objects' },
  { emoji: '📟', name: 'pager', keywords: ['pager', 'beep'], category: 'objects' },
  { emoji: '📠', name: 'fax', keywords: ['fax', 'machine'], category: 'objects' },
  { emoji: '🔋', name: 'battery', keywords: ['battery', 'power'], category: 'objects' },
  { emoji: '🔌', name: 'electric_plug', keywords: ['plug', 'electric'], category: 'objects' },
  { emoji: '💻', name: 'computer', keywords: ['computer', 'laptop'], category: 'objects' },
  { emoji: '🖥️', name: 'desktop_computer', keywords: ['computer', 'desktop'], category: 'objects' },
  { emoji: '🖨️', name: 'printer', keywords: ['printer', 'print'], category: 'objects' },
  { emoji: '⌨️', name: 'keyboard', keywords: ['keyboard', 'type'], category: 'objects' },
  { emoji: '🖱️', name: 'computer_mouse', keywords: ['mouse', 'computer'], category: 'objects' },
  { emoji: '🖲️', name: 'trackball', keywords: ['trackball', 'mouse'], category: 'objects' },
  { emoji: '🕹️', name: 'joystick', keywords: ['joystick', 'game'], category: 'objects' },
  { emoji: '🗜️', name: 'clamp', keywords: ['clamp', 'tool'], category: 'objects' },
  { emoji: '💾', name: 'floppy_disk', keywords: ['disk', 'save'], category: 'objects' },
  { emoji: '💿', name: 'cd', keywords: ['cd', 'disk'], category: 'objects' },
  { emoji: '📀', name: 'dvd', keywords: ['dvd', 'disk'], category: 'objects' },
  { emoji: '📼', name: 'vhs', keywords: ['vhs', 'tape'], category: 'objects' },
  { emoji: '📷', name: 'camera', keywords: ['camera', 'photo'], category: 'objects' },
  { emoji: '📸', name: 'camera_flash', keywords: ['camera', 'flash'], category: 'objects' },
  { emoji: '📹', name: 'video_camera', keywords: ['video', 'camera'], category: 'objects' },
  { emoji: '🎥', name: 'movie_camera', keywords: ['movie', 'camera'], category: 'objects' },
  { emoji: '📽️', name: 'film_projector', keywords: ['projector', 'film'], category: 'objects' },
  { emoji: '🎞️', name: 'film_strips', keywords: ['film', 'strips'], category: 'objects' },
  { emoji: '🔍', name: 'mag', keywords: ['magnifying', 'glass'], category: 'objects' },
  { emoji: '🔎', name: 'mag_right', keywords: ['magnifying', 'glass'], category: 'objects' },
  { emoji: '🕯️', name: 'candle', keywords: ['candle', 'light'], category: 'objects' },
  { emoji: '💡', name: 'light_bulb', keywords: ['light', 'bulb', 'idea'], category: 'objects' },
  { emoji: '🔦', name: 'flashlight', keywords: ['flashlight', 'torch'], category: 'objects' },
  { emoji: '🪔', name: 'diya_lamp', keywords: ['diya', 'lamp'], category: 'objects' },
  { emoji: '🪔', name: 'diya_lamp', keywords: ['diya', 'lamp'], category: 'objects' },
  { emoji: '🧯', name: 'fire_extinguisher', keywords: ['fire', 'extinguisher'], category: 'objects' },
  { emoji: '🪔', name: 'diya_lamp', keywords: ['diya', 'lamp'], category: 'objects' },
  { emoji: '🪔', name: 'diya_lamp', keywords: ['diya', 'lamp'], category: 'objects' },
];

export const EMOJI_CATEGORIES = [
  { id: 'smileys', name: 'Smileys & People', icon: '😀' },
  { id: 'animals', name: 'Animals & Nature', icon: '🐶' },
  { id: 'gestures', name: 'People & Body', icon: '👋' },
  { id: 'symbols', name: 'Symbols', icon: '❤️' },
  { id: 'food', name: 'Food & Drink', icon: '🍕' },
  { id: 'travel', name: 'Travel & Places', icon: '✈️' },
  { id: 'activities', name: 'Activities', icon: '⚽' },
  { id: 'objects', name: 'Objects', icon: '💡' },
];

export function getEmojisByCategory(category: string): EmojiItem[] {
  return EMOJI_DATA.filter(emoji => emoji.category === category);
}

export function searchEmojis(query: string): EmojiItem[] {
  if (!query.trim()) return [];
  
  const lowerQuery = query.toLowerCase();
  return EMOJI_DATA.filter(emoji => 
    emoji.name.toLowerCase().includes(lowerQuery) ||
    emoji.keywords.some(kw => kw.toLowerCase().includes(lowerQuery))
  ).slice(0, 50);
}
